
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class load extends javax.swing.JFrame implements Runnable{
    Connection conn;
        Thread th;
        int s;
        public void setUploading(){
th.start();

}

    /**
     * Creates new form load
     */
    public load() {
        initComponents();
        this.setLocationRelativeTo(null);
        th = new Thread((Runnable)this);
        setUploading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pgbar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 578));
        jPanel1.setLayout(null);

        pgbar.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pgbar);
        pgbar.setBounds(280, 620, 750, 20);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 2, 48)); // NOI18N
        jLabel2.setText("AIRLINE RESERVATION SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 50, 790, 110);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel4.setText("Presented by Haram Niaz and Sana Mateen");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(960, 670, 380, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/last size.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 578));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-370, 0, 1730, 740);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1050, 540, 41, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new load().setVisible(true);}
         
         
            public void run() {
               try{
               
                  for(int  i=0; i<200; i++){
                    s = s+i;
                    int m = pgbar.getMaximum();
                    int v = pgbar.getValue();
                    if(v<m){
                    pgbar.setValue(pgbar.getValue()+1);
                    }else{
                    i=201;
                    setVisible(false);
                    new loginas().setVisible(true);
                    }
                    Thread.sleep(50);
                  }  
               }    
                            
              catch(Exception e){
                       System.out.println(e);
               }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar pgbar;
    // End of variables declaration//GEN-END:variables
}
